name: ollama

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "22345:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        ollama serve & 
        sleep 2 &&
        ollama pull deepseek-r1:1.5b &&
        tail -f /dev/null

  flask-app:
    build: .
    container_name: flask-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - ollama

volumes:
  ollama_data:
