name: ai-agents

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    environment:
      OLLAMA_HOST: 0.0.0.0
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - "11434:11434"
    runtime: nvidia
    networks:
      - app-network
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        ollama serve & 
        sleep 2 &&
        tail -f /dev/null
      # ollama pull deepseek-r1:1.5b &&
      # ollama pull deepseek-r1:7b &&
      # ollama pull deepseek-r1:8b &&

  flask-app:
    build: .
    container_name: flask-app
    restart: unless-stopped
    ports:
      - "7001:7000" # This maps the host's 7001 to the container's 7000
    volumes:
      - .:/app
    depends_on:
      - ollama
    networks:
      - app-network

volumes:
  ollama_data:


networks:
  app-network:
    driver: bridge
